spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/jdbc
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.username=nicky
spring.datasource.password=tellmeyourname
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

app.secret-key=rsR9DhIaUbbd4Lj1kbqgul1QzbhXTQiIBRF4Z3L0qTA8ajrdAf71OHmoVS5EWbfTiWBKLpN4LtfPWFCCn6tudQ==
app.expiration-time=900000
